### ISSUE TITLE
HUD Compliments 

### ISSUE THREAD

**Issue by Seranok** [Eniere/idhud#1]
Howdy Eniere. I love the hud and everything because truth be told only the default hud could create a picture in my head. I used the other huds but was disappointed. Guess Im a default hud person. I started using your hud until I saw it on featured on huds.tf pags.
The thing is I cant keep up with the maintenance and optimization updates. Can you create an updater or some sort? An .exe file. 
5/5

**Comment by Eniere** [comment]
Thank you very much for your kind words! 

I've already planned to create an installer, but I can't say exactly when it will happen.

**Comment by Seranok** [comment]
I assume you know a lot of heavy coding eniere. However with all respects, I would love to see the installer before tf invasion update which will arrive this Friday. Sunday by latest. Keep up the good work and the excellent support you are giving to users. By the way I think the server control panel and demo ui buttons, choosing crosshairs could be chosen in the installer dont you think.
Anyway I have a question,nis this hud optimized for 1368x768 resolutions? My pc runs on that Frame.

**Comment by Eniere** [comment]
Yes, it support resolutions from 720p to 1080p

**Comment by Seranok** [comment]
So I can expect the installer to be up before next Friday?
