### ISSUE TITLE
Installation not working?

### ISSUE THREAD

**Issue by xAgent69x** [Eniere/idhud#13]
I've followed all of the instructions correctly, but the HUD isn't working. Can someone help me?

**Comment by Eniere** [comment]
Hello, [xAgent69x](https://github.com/xAgent69x)!

What's gone wrong?

**Comment by Tiagoquix** [comment]
You probably installed it this way:

tf\custom\idhud\idhud\(files)

There shouldn't be two HUD folders, just one.
