### ISSUE TITLE
integrate changes from TF2 Community HUD fixes

### ISSUE THREAD

**Issue by tauin** [Eniere/idhud#18]
https://github.com/CriticalFlaw/TF2HUD.Fixes/ contains numerous fixes in tf2's default hud, do you think it would be possible to integrate its changes into improved default?

**Comment by tauin** [comment]
there are also a couple changes in the community edition that could come over nicely without much fuss

**Comment by Eniere** [comment]
Thanks for the suggestion! I'll see what can be integrated into idHUD
