### ISSUE TITLE
Glitched Paints

### ISSUE THREAD

**Issue by Mechman42** [Eniere/idhud#3]
I noticed an issue after recently downloading the HUD. When previewing my loadouts in the menu, the RED/BLU buttons change the colors of any cosmetics as well as the default model, but any team-colored war paint or cosmetic paints are not changed (presumably along with team shine killstreak, but I don't have any to check.)

**Comment by Tiagoquix** [comment]
This is a problem with the `r_skin` command, not a HUD issue.
